---

apiVersion: v2
description: A task to create a spring application.
name: springdemo
version: "0.1.2"
mainteiners:
- name:  cod-panda
home: "https://github.com/cod-panda/kube-SpecialTask"
keywords:
- spring-boot
- helm
appversion: "0.1.2"
icon: "https://cdn.icon-icons.com/icons2/3123/PNG/128/forest_tree_nature_garden_wood_spring_icon_191955.png"
...
