---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default "default" .Values.namespace }}
  labels:
    app: {{ .Values.selector }}
spec:
  replicas: {{ default 3 .Values.appspecs.replicas }}
  revisionHistoryLimit: {{ default 5 .Values.appspecs.revisionsLimit }}
  selector:
    matchLabels:
      app: {{ .Values.selector }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default 1 .Values.strategy.additionalReplicas }}
      maxUnavailable: {{ default 1 .Values.strategy.maxUnavailable }}
    type: {{ default "RollingUpdate" .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        name: {{ default "springboot_app" .Values.name }}
        livenessProbe:
          failureThreshold: {{ default 3 .Values.service.failures }}
          httpGet:
            path: {{ default "/hello" .Values.service.path }}
            port: {{ default 8080 .Values.service.targetPort }}

