---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemo
  namespace: default
  labels:
    app: springdemo
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: springdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springdemo
    spec:
      containers:
      - image: docker.io/cod4panda/springboot_app:demo
        imagePullPolicy: IfNotPresent
        name: springboot-app-qk9ml
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hello
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springdemo
  name: springdemo
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.239.62
  clusterIPs:
  - 10.111.239.62
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31162
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springdemo
  sessionAffinity: None
  type: LoadBalancer

...
